artifacts_root: artifacts
root_directory: artifacts/data_ingestion
source_url: https://github.com/krunalss/dataset_it_entep/raw/master/Training_Batch_Files.zip
local_data_file: artifacts/data_ingestion/data.zip
unzip_dir: artifacts/data_ingestion
good_data_folder : artifacts/training_data/Good_Data_Folder
bad_data_folder : artifacts/training_data/Bad_Data_Folder
saved_model : artifacts/trained_models
load_model  : artifacts\trained_models\xgboost_model.pkl
prediction_dir : saved_artifacts\prediction_dir
output_dir : artifacts/output